//
//  ExamQuestions.m
//  MobileDeviceiPAS
//
//  Created by Ｍasqurin on 2017/7/19.
//  Copyright © 2017年 Ｍasqurin. All rights reserved.
//

#import "ExamQuestions.h"

@implementation ExamQuestions
-(void)aaa{
    NSArray *test = @[@{@"subject":@"考科 1:行動裝置概論-參考樣題",
                        @"testPaper":
@[@{@"questionNumber":@"1",
      @"topic":@"針對「MDM (Mobile Device Management)」，下列哪一個選項的敘述正確?",
      @"A":@"一種行動裝置廣告追蹤管理方案",
      @"B":@"一種行動裝置管理解決方案",
      @"C":@"一種多重感知偵測的管理方案",
      @"D":@"一種多重螢幕顯示的管理方案",
      @"answer":@"B"},
  @{@"questionNumber":@"2",
    @"topic":@"針對「G-Sensor」，下列哪一個選項的敘述正確?",
    @"A":@"一種提供全球定位資訊的感測器",
    @"B":@"一種提供方位角資訊的感測器",
    @"C":@"一種提供物體在加速過程中作用在物體上的力，比如晃動、跌落、上升、下降等各種位移變化的感測器",
    @"D":@"以上皆是",
    @"answer":@"C"},
  @{@"questionNumber":@"3",
    @"topic":@"針對「NFC」，下列哪一個選項的敘述錯誤?",
    @"A":@"為 Near Field Communication 的縮寫",
    @"B":@"一種長距離的高頻無線通訊技術",
    @"C":@"一種短距離的高頻無線通訊技術",
    @"D":@"與藍牙技術相比，NFC的可傳輸距離較短且設定連線時間較短",
    @"answer":@"B"},
  @{@"questionNumber":@"4",
    @"topic":@"針對「Open data」，下列哪一個選項的敘述正確?",
    @"A":@"一種經過挑選與許可的資料，這些資料受著作權、專利權限制，任何人都可以自由使用",
    @"B":@"一種經過挑選與許可的資料，這些資料不受著作權、專利權限制，任何人都可以自由使用",
    @"C":@"一種不經過挑選與許可的資料，這些資料受著作權、專利權限制，任何人都可以自由使用",
    @"D":@"一種不經過挑選與許可的資料，這些資料不受著作權、專利權限制，任何人可以自由使用",
    @"answer":@"B"},
  @{@"questionNumber":@"5",
    @"topic":@"請問下列何者為 SIM 卡的辨識碼?",
    @"A":@" ICCID (Integrate Circuit Card Identity)",
    @"B":@"IMEI (International Mobile Equipment Identification Number)",
    @"C":@" PIN (Personal Identification Number)",
    @"D":@"PUK (Personal Identification Number Unlock Key)",
    @"answer":@"A"},
  @{@"questionNumber":@"6",
    @"topic":@"以下何者非行動裝置間可以用來做資料交換的技術?",
    @"A":@"Wi-Fi",
    @"B":@"Bluetooth",
    @"C":@"NFC",
    @"D":@"iBeacon",
    @"answer":@"D"},
  @{@"questionNumber":@"7",
    @"topic":@"在智慧型手機中，有一組所謂行動電話的身份證，用於識別每一部獨立的 手機等行動通訊裝置，稱之為?",
    @"A":@"國際移動設備識別碼 (IMEI, International Mobile Equipment Identity)",
    @"B":@"MAC 地址 (Media Access Control Address)",
    @"C":@"數位簽章 (Digital Signature)",
    @"D":@"建置號碼 (Build Number)",
    @"answer":@"A"},
  @{@"questionNumber":@"8",
    @"topic":@"下列何者可用於接聽電話時自動關閉 LCD 螢幕以節省電量?",
    @"A":@"GPS (Global Positioning System/Motion Sensor)",
    @"B":@"觸碰壓力感應器 (Touch Pressure Sensor)",
    @"C":@"接近感應器(ProximitySensor)",
    @"D":@"以上皆非",
    @"answer":@"C"},
  @{@"questionNumber":@"9",
    @"topic":@"下列哪個手機攝影影像畫質訊號源為 FHD (Full HD)?",
    @"A":@"720x480 (480p)",
    @"B":@"1280x720 (720p)",
    @"C":@"1920x1080 (1080p)",
    @"D":@"3840× 2160",
    @"answer":@"C"},
  @{@"questionNumber":@"10",
    @"topic":@"打開飛航模式時，手機會關掉以下哪些通訊方式?",
    @"A":@"3G/4G",
    @"B":@"Wi-Fi",
    @"C":@"Bluetooth",
    @"D":@"以上皆是",
    @"answer":@"D"},
  @{@"questionNumber":@"11",
    @"topic":@"針對行動裝置的無線充電技術，下列描述何者不正確?",
    @"A":@"若手機沒有搭配特殊的芯片，則沒有任何方法讓該手機也可以無線充電",
    @"B":@"需要手機搭配特殊的芯片才可以使用該功能",
    @"C":@"現在的手機只要升級作業系統後即可使用無線充電",
    @"D":@"無線充電的電源轉換效率比有線充電還低",
    @"answer":@"C"},
  @{@"questionNumber":@"12",
    @"topic":@"關於行動裝置的敘述，下列何者不正確?",
    @"A":@"使用 GPS 定位時，GPS 衛星會主動發送訊號給手機定位",
    @"B":@"除了 GPS 定位外，我們也可以使用 Wi-Fi 來協助手機來定位",
    @"C":@"行動網路除了可以上網外，亦可協助手機來定位",
    @"D":@"使用 GPS 定位時，手機會發送訊號給 GPS 衛星來要求位置資訊",
    @"answer":@"D"},
  @{@"questionNumber":@"13",
    @"topic":@"以下何者可以提供行動裝置用來偵測是否螢幕需要做自動旋轉方向?",
    @"A":@"接近感應器 (Proximity Sensor)",
    @"B":@"加速度感應器 (G-sensor/Accelerometer)",
    @"C":@"磁力感應器 (M-sensor)",
    @"D":@"氣壓感應器 (bBarometer)",
    @"answer":@"B"},
  @{@"questionNumber":@"14",
    @"topic":@"現在人們常用的行動裝置，如:智慧型手機、平板電腦，皆無需使用任何 的工具便可操作，請問現今多數螢幕的觸控面板的技術為何?",
    @"A":@"聲波式觸控螢幕",
    @"B":@"電容式觸控螢幕",
    @"C":@"電阻式觸控螢幕",
    @"D":@"紅外線式觸控螢幕",
    @"answer":@"B"},
  @{@"questionNumber":@"15",
    @"topic":@"目前在智慧型手機上使用的作業系統，不包含哪一個?",
    @"A":@"Android",
    @"B":@"iOS",
    @"C":@"FirefoxOS",
    @"D":@"Chrome OS",
    @"answer":@"D"},
  @{@"questionNumber":@"16",
    @"topic":@"下列何者較適合智慧型手機程式作為資料交換的格式?",
    @"A":@"XML",
    @"B":@"C++",
    @"C":@"Java",
    @"D":@"HTML",
    @"answer":@"A"},
  @{@"questionNumber":@"17",
    @"topic":@"除了 XML 以外，智慧型手機也可使用下列何種資料交換語言去儲存和傳 送簡單結構資料?",
    @"A":@"ASP",
    @"B":@"C++",
    @"C":@"JSON (JavaScript Object Notation)",
    @"D":@"Java",
    @"answer":@"C"},
  @{@"questionNumber":@"18",
    @"topic":@"下列何者是智慧型手機常用的分散式軟體系統架構樣式，主要使用 XML 或 JSON 等簡單介面的 Web 服務，漸漸取代 SOAP 的 Web 服務，成為 WWW 上最常使用的 Web 服務模型?",
    @"A":@"REST(REpresentationalStateTransfer)",
    @"B":@"ODBC (Open DataBase Connectivity)",
    @"C":@"OAuth",
    @"D":@"HTTP",
    @"answer":@"A"},
  @{@"questionNumber":@"19",
    @"topic":@"現行行動裝置所使用的 Wi-Fi 技術中，何者可以用多個天線收發資料?",
    @"A":@"802.11b",
    @"B":@"802.11g",
    @"C":@"802.11n",
    @"D":@"以上皆非",
    @"answer":@"C"},
  @{@"questionNumber":@"20",
    @"topic":@"關於智慧型手機上的光度感測器，下列敘述何者錯誤?",
    @"A":@"可以用來偵測環境光源的位置",
    @"B":@"可以調節螢幕較適合的顯示亮度",
    @"C":@"可以偵測拍攝時是否需要閃光燈",
    @"D":@"可以間接用來感應觸碰螢幕是否被物體所遮蔽",
    @"answer":@"A"},
  @{@"questionNumber":@"21",
    @"topic":@"行動支付系統中所應具備的軟/硬體設備中，不含下列那一項?",
    @"A":@"付款轉接站 (Payment Gateway)",
    @"B":@"認證中心 (CertificationAuthority)",
    @"C":@"電子錢包 (Electronic Wallet)",
    @"D":@"檔案傳輸協定 (File Transfer Protocol)",
    @"answer":@"D"},
  @{@"questionNumber":@"22",
    @"topic":@"在行動商務 App 電子商場進行線上購物，下列程序何者較符合現況?",
    @"A":@"將選購商品放入購物籃→選購完成確認訂單數量及金額→瀏覽商品→填寫付款資料→選擇付款方式→送出訂單",
    @"B":@"瀏覽商品→選購完成確認訂單數量及金額→選擇付款方式→填寫付款資料→將選購商品放入購物籃→送出訂單",
    @"C":@"瀏覽商品→將選購商品放入購物籃→選購完成確認訂單數量及金額→選擇付款方式→填寫付款資料→送出訂單",
    @"D":@"選擇付款方式→填寫付款資料→瀏覽商品→將選購商品放入購物籃→選購完成確認訂單數量及金額→送出訂單",
    @"answer":@"C"},
  @{@"questionNumber":@"23",
    @"topic":@"若某一智慧型手機程式以 JSON 作為資料交換格式，請問下列何者為此程 式可閱讀的資料?",
    @"A":@"<note> <to>Tove</to><from>Jani</from> <heading>Reminder</heading><body>Don't forget me this weekend!</body></note>",
    @"B":@"{'subject':'Math','score':80}",
    @"C":@"0/4/5/2/7/8/3",
    @"D":@"以上皆是",
    @"answer":@"B"},
  @{@"questionNumber":@"24",
    @"topic":@"請問有關行動裝置上 NFC 的應用，不包含下列何項?",
    @"A":@"行動支付",
    @"B":@"檔案傳輸",
    @"C":@"裝置配對",
    @"D":@"分享網路",
    @"answer":@"D"},
  @{@"questionNumber":@"25",
    @"topic":@"下列何者不是主要的 Business-to-Customer (B2C)類別行動裝置 App?",
    @"A":@"博客來書局 APP",
    @"B":@"Amazon APP",
    @"C":@"eBay APP",
    @"D":@"燦坤快8 APP",
    @"answer":@"C"},
  @{@"questionNumber":@"26",
    @"topic":@"若一智慧型手機利用兩聲道錄音，鎂秒採樣憑綠為44.1kHz，每個樣本使用 16bit，採用 mp4 壓縮 (壓縮比大約 1/20)，則 10 秒鐘的錄音大約會產 生多大的錄音檔?",
    @"A":@"約 7 kbit",
    @"B":@"約 70 kbit",
    @"C":@"約 700 kbit",
    @"D":@"約 1.4 Mbit",
    @"answer":@"C"},
  @{@"questionNumber":@"27",
    @"topic":@"假設一台智慧手機電池容量為 2,000mAh，行動電源的電源容量為 10,000mHa，行動電源的電源轉換率為 60%，則此行動電源可以充滿完全 沒電的手機幾次呢?",
    @"A":@"3 次",
    @"B":@"6 次",
    @"C":@"8 次",
    @"D":@"10 次",
    @"answer":@"A"},
  @{@"questionNumber":@"28",
    @"topic":@"若網管人員將無線設備升級至 IEEE 802.11n 後，請問，原來使用 IEEE 802.11a、 IEEE 802.11b 或 IEEE 802.11g 網卡的使用者，何者仍可以繼續 無線上網?",
    @"A":@"只有 IEEE 802.11a 與 IEEE 802.11b",
    @"B":@"只有 IEEE 802.11b 與 IEEE 802.11g",
    @"C":@"只有 IEEE 802.11g",
    @"D":@"三者皆可",
    @"answer":@"D"},
  @{@"questionNumber":@"29",
    @"topic":@"當單一基地台用戶過多時， 該基地台運作上會如何處理?",
    @"A":@"無變化，使用者不受影響",
    @"B":@"其他基地台將自動擴大涵蓋範圍，對使用者不造成影響",
    @"C":@"擴大涵蓋範圍，造成靠近該基地台之使用者訊號不佳",
    @"D":@"縮小涵蓋範圍，造成與其他基地台交接範圍區域的使用者訊號不佳",
    @"answer":@"D"},
  @{@"questionNumber":@"30",
    @"topic":@"下列何者不是行動商務的組成要素?",
    @"A":@"使用者端行動化的通訊裝置",
    @"B":@"可支援行動商務活動的網路架構與資訊平台",
    @"C":@"適合用來播放高畫質電視 (4k/8k)的影音平台",
    @"D":@"相關的行動式應用與服務及其商業模式",
    @"answer":@"C"},
  @{@"questionNumber":@"31",
    @"topic":@"下列何者是現在 WLAN 常見的連線技術?",
    @"A":@"Bluetooth",
    @"B":@"WiMax",
    @"C":@"4G",
    @"D":@"Wi-Fi",
    @"answer":@"D"},
  @{@"questionNumber":@"32",
    @"topic":@"依照傳輸技術規格的速率快慢排序，下列何者正確?",
    @"A":@"4G > Wi-Fi > Bluetooth",
    @"B":@"4G > Bluetooth > Wi-Fi",
    @"C":@"Wi-Fi > 4G > Bluetooth",
    @"D":@"Bluetooth > 4G > Wi-Fi",
    @"answer":@"C"},
  @{@"questionNumber":@"33",
    @"topic":@"以下何者是HTTPS 協定所使用的加密方式?",
    @"A":@"DES",
    @"B":@"RSA",
    @"C":@"SSL",
    @"D":@"3DES",
    @"answer":@"C"},
  @{@"questionNumber":@"34",
    @"topic":@"下列何者是使用 UDP (User Datagram Protocol)協定之服務?",
    @"A":@"DNS (Domain Name System)",
    @"B":@"FTP (File Transfer Protocol)",
    @"C":@"Telnet",
    @"D":@"SMTP (Simple Mail Transfer Protocol)",
    @"answer":@"A"},
  @{@"questionNumber":@"35",
    @"topic":@"當行動裝置通話或數據使用過程中，會從一個基地台覆蓋的區域移動到另一個基地台覆蓋的區域，這過程稱之為何?",
    @"A":@"漫遊 (Roaming)",
    @"B":@"展頻 (Spread Spectrum)",
    @"C":@"換手 (Handover or Handoff)",
    @"D":@"連線 (Connection)",
    @"answer":@"C"},
  @{@"questionNumber":@"36",
    @"topic":@"下列關於 LTE (Long Term Evolution)的敘述，何者錯誤?",
    @"A":@"LTE 標準中不支援電路交換技術 (Circuit Switched)，故無法直接使用 語音通話",
    @"B":@"相較於WiMAX，LTE為現今的4G主流技術",
    @"C":@"VoLTE是利用LTE的網絡的封包機換來產生語音通話",
    @"D":@"LTE與Wi-Fi只是在傳輸上的技術有所不同，故Wi-FiAP可以直接當4G 基地台",
    @"answer":@"D"},
  @{@"questionNumber":@"37",
    @"topic":@"以下何者不是常用的 HTTP Web Service 所支援的方法?",
    @"A":@"GET",
    @"B":@"POST",
    @"C":@"PUT",
    @"D":@"TRANSFER",
    @"answer":@"D"},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{@"questionNumber":@"",
    @"topic":@"",
    @"A":@"",
    @"B":@"",
    @"C":@"",
    @"D":@"",
    @"answer":@""},
  @{}]},
  @{},
  @{}];
    
    
    
    
    NSLog(@"%@",test);
}
@end
